CREATE DATABASE DietVirutCorona
GO

USE DietVirutCorona
GO

CREATE TABLE Player (
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1) ,
	Name NVARCHAR(60) NOT NULL,
	Email NVARCHAR(60) NOT NULL,
	UserName NVARCHAR(60) NOT NULL,
	PassWord NVARCHAR(60) NOT NULL,
	Status INT NOT NULL
	
)
GO

CREATE TABLE Character (
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1) ,
	PlayerID INT FOREIGN KEY REFERENCES Player(ID) NOT NULL,
	Level INT NOT NULL,
	State INT NOT NULL,
	Heart INT NOT NULL,
	Live INT NOT NULL,
	Exp INT NOT NULL,
	Total INT NOT NULL,
	Point INT NOT NULL,
	Time INT NOT NULL
)
GO
CREATE TABLE HighScore(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1) ,
	PlayerID INT FOREIGN KEY REFERENCES Player(ID) NOT NULL,
	HighPoint INT NOT NULL,
)
GO
CREATE TABLE admin(
	AdminID INT PRIMARY KEY NOT NULL IDENTITY(1,1) ,
	Name NVARCHAR(60) NOT NULL,
	UserName NVARCHAR(60) NOT NULL,
	PassWord NVARCHAR(60) NOT NULL,
	Email NVARCHAR(60) NOT NULL,
	Position NVARCHAR(20) NOT NULL
)
GO
INSERT INTO admin (Name, UserName, PassWord,Email,Position)
VALUES ('Hung12', 'Hung12', 'Hung12','Hung12','SuperAdmin');
GO