/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Connection.ConnectMySQL;
import Model.Admin;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Form.SelectSever.a;
import java.util.ArrayList;
import java.util.List;

public class LoginForm extends javax.swing.JFrame {

    public static boolean i;
    public static int re;
    public static String UserN;
    public static String PassW;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        setUndecorated(true);
        setResizable(false);
        setLocation((screenWidth - 730) / 2, (screenHeight - 460) / 2);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        loginicon = new javax.swing.JLabel();
        NAME_GAME = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        txt_USER = new javax.swing.JTextField();
        txt_PASS = new javax.swing.JPasswordField();
        bt_LOGIN = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 40));

        user.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Tài khoản :");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 100, 40));

        loginicon.setIcon(new javax.swing.ImageIcon("D:\\HK2\\ADF-II\\BT\\AppQtri\\src\\Image\\LoginForm1.png")); // NOI18N
        jPanel1.add(loginicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 70, 80));

        NAME_GAME.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        NAME_GAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME_GAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NAME_GAME.setText("Diệt Trừ Virut CORONA");
        jPanel1.add(NAME_GAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 100));

        pass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Mật khẩu :");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 100, 30));

        txt_USER.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_USERActionPerformed(evt);
            }
        });
        jPanel1.add(txt_USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 170, 40));

        txt_PASS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PASSActionPerformed(evt);
            }
        });
        jPanel1.add(txt_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, 40));

        bt_LOGIN.setBackground(new java.awt.Color(153, 204, 255));
        bt_LOGIN.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_LOGIN.setText("ĐĂNG NHẬP");
        bt_LOGIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LOGINActionPerformed(evt);
            }
        });
        jPanel1.add(bt_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 110, 30));

        background.setIcon(new javax.swing.ImageIcon("D:\\HK2\\ADF-II\\BT\\AppQtri\\src\\Image\\LoginForm.png")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_USERActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_USERActionPerformed

    private void bt_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LOGINActionPerformed

        String user = txt_USER.getText();
        char[] getpass = txt_PASS.getPassword();
        String pass = String.valueOf(getpass);
        System.out.println(user);
        System.out.println(pass);

        Connection conn = ConnectMySQL.getConnect(a);
        String sql = "SELECT * FROM admin where UserName='" + user + "'and PassWord='" + pass + "'";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {

                UserN = rs.getString(3);
                PassW = rs.getString(4);
            } else {
            };
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        if (user.equals(UserN) && pass.equals(PassW)) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Information info = new Information();
                    info.KhoiTaoPlayer();
                    info.setVisible(true);
                    
                }
            });
            setVisible(false);
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Tài khoản mật khẩu chưa chính xác");
        }


    }//GEN-LAST:event_bt_LOGINActionPerformed

    private void txt_PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PASSActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_PASSActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    public static void main(String args[]) throws SQLException {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new SelectSever().setVisible(true);

            }
        });

        /*
        //connect database
          Connection conn=ConnectMySQL.getConnect();
             String sql = "INSERT INTO admin (AdminID, Name,UserName, PassWord,Email) VALUES (NULL, ?,?,?,?);";

            PreparedStatement pst = conn.prepareStatement(sql);
             pst.setString(1,Name);
            pst.setString(2, User);
            pst.setString(3,PassWord );
            pst.setString(4,Email);
          r = pst.executeUpdate();
          pst.close();
            conn.close();
        
        //

         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAME_GAME;
    private javax.swing.JLabel background;
    private javax.swing.JButton bt_LOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginicon;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField txt_PASS;
    private javax.swing.JTextField txt_USER;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
